services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
  frontend:
    build: ./frontend/
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5173:5173
    depends_on:
      - redis

volumes:
  redis_data:
