services:
  backend:
    build: ./backend/
    ports:
      - 4000:4000
    volumes:
      - ./backend/:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules

  frontend:
    build: ./frontend/
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5173:5173

volumes:
  backend_node_modules:
